test_PROGRAMS = d1node2 d1node3


d1node2_SOURCES = node.c macan_config.c
d1node2_CPPFLAGS = -DNODE_ID=2
d1node2_LIBS = macan nettle rt

d1node3_SOURCES = node.c macan_config.c
d1node3_CPPFLAGS = -DNODE_ID=3
d1node3_LIBS = macan nettle rt

shared_LIBRARIES = demo01cfg
demo01cfg_SOURCES = macan_config.c
demo01cfg_CPPFLAGS = -DNODE_ID=0xff
