test_PROGRAMS = demo_cosummit_node btnvis
lib_LOADLIBES = macan nettle rt ev
demo_cosummit_node_SOURCES = d3node.c macan_config.c ltk_tc.c

btnvis_SOURCES = btnvis.c
btnvis_LIBS = curses

shared_LIBRARIES = demo_cosummit_cfg
demo_cosummit_cfg_SOURCES = macan_config.c

shared_LIBRARIES += demo_cosummit_keys
demo_cosummit_keys_SOURCES = ltk_ts.c ltk_pc.c ltk_tc.c

shared_LIBRARIES += demo_cosummit_tskey
demo_cosummit_tskey_SOURCES = ltk_ts.c

