test_PROGRAMS = attack-scenario attacker-gw

attack-scenario_SOURCES = attack-scenario.c cfg.c
attacker-gw_SOURCES = attacker-gw.c cfg.c
attacker-gw_CFLAGS = $(OMK_CFLAGS) -Wno-strict-aliasing

lib_LOADLIBES = macan ev nettle
