test_PROGRAMS = d2node2 d2node3

d2node2_SOURCES = node.c macan_config.c
d2node2_CPPFLAGS = -DNODE_ID=0
d2node2_LIBS = macan nettle rt

d2node3_SOURCES = node.c macan_config.c
d2node3_CPPFLAGS = -DNODE_ID=3
d2node3_LIBS = macan nettle rt

shared_LIBRARIES = demo02cfg
demo02cfg_SOURCES = macan_config.c
