test_PROGRAMS = d2node2 d2node3

d2node2_SOURCES = node.c macan_config.c ltk2.c
d2node2_CPPFLAGS = -DNODE_ID=2
d2node2_LIBS = macan nettle rt

d2node3_SOURCES = node.c macan_config.c ltk3.c
d2node3_CPPFLAGS = -DNODE_ID=3
d2node3_LIBS = macan nettle rt

shared_LIBRARIES = demo02cfg
demo02cfg_SOURCES = macan_config.c

shared_LIBRARIES += demo02keys
demo02keys_SOURCES = ltk2.c ltk3.c ltk1.c

shared_LIBRARIES += demo02tskey
demo02tskey_SOURCES = ltk1.c
