bin_PROGRAMS = keysvr timesvr macanmon
keysvr_SOURCES = keysvr.c
keysvr_LIBS = macan

timesvr_SOURCES = timesvr.c
timesvr_LIBS = macan

macanmon_SOURCES = macanmon.c
macanmon_LIBS = macan

lib_LOADLIBES = nettle rt dl
