test_PROGRAMS = d3node btnvis
lib_LOADLIBES = macan nettle rt
d3node_SOURCES = d3node.c macan_config.c ltk4.c

btnvis_SOURCES = btnvis.c
btnvis_LIBS = curses

shared_LIBRARIES = demo03cfg
demo03cfg_SOURCES = macan_config.c
